version: 2.1
jobs:
  build:
    machine: true

    working_directory: ~/rust-demo

    steps:
      - checkout
      - run:
          name: Setup build environment
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake binutils-dev libcurl4-openssl-dev libiberty-dev libelf-dev libdw-dev
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y;
            export PATH=~/.cargo/bin:$PATH
            rustup install stable
            rustup default stable
          no_output_timeout: 1800s
      - run:
          name: Format
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add rustfmt
            cargo fmt --all -- --check
      - run:
          name: Clippy
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add clippy
            cargo clippy --all -- -D warnings
      - run:
          name: Test
          command: |
            export PATH=~/.cargo/bin:$PATH
            export RUST_BACKTRACE=1
            cargo test
      - run:
          name: Coverage
          command: |
            export PATH=~/.cargo/bin:$PATH
            # install kcov
            cargo install cargo-kcov
            cargo kcov --print-install-kcov-sh | sh
            echo "Install kcov successfully"
            # coverage
            cargo kcov --all -v
            bash <(curl -s https://codecov.io/bash)
            echo "Upload code coverage successfully"
      
workflows:
  version: 2.1
  build:
    jobs:
      - build